### ISSUE TITLE
no required module provides package

### ISSUE THREAD

**Issue by medlaam** [vivekganesan01/ganache-cli-block-explorer#1]
hi, thanks for sharing, can you help with this

 go run router.go
router.go:16:2: no required module provides package github.com/ethereum/go-ethereum/common: go.mod file not found in current directory or any parent directory; see 'go help modules'
router.go:17:2: no required module provides package github.com/ethereum/go-ethereum/core/types: go.mod file not found in current directory or any parent directory; see 'go help modules'
router.go:18:2: no required module provides package github.com/ethereum/go-ethereum/ethclient: go.mod file not found in current directory or any parent directory; see 'go help modules'
router.go:19:2: no required module provides package github.com/gorilla/mux: go.mod file not found in current directory or any parent directory; see 'go help modules'

thanks

**Comment by dparadox** [comment]
@medlaam it's missing the dependencies, use go get
go get github.com/ethereum/go-ethereum/common github.com/ethereum/go-ethereum/core/types github.com/ethereum/go-ethereum/ethclient github.com/gorilla/mux

**Comment by leovafme** [comment]
![imagen](https://user-images.githubusercontent.com/17578723/123677242-7e968b80-d80a-11eb-9da6-553f5106709e.png)

**Comment by leovafme** [comment]
add go mod 
`go mod init ganache-cli-block-explorer`

install deps
`go get github.com/ethereum/go-ethereum/common github.com/ethereum/go-ethereum/core/types github.com/ethereum/go-ethereum/ethclient github.com/gorilla/mux`

it has worked for me
